/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paperclicker;

import javax.swing.ImageIcon;

/**
 *
 * @author Alex Vasil
 */
public class PaperClickerFrame extends javax.swing.JFrame {
    private double clickCounter;
    private double papersCounter;
    private boolean initClickTime;
    private long firstClickTime;
    private int autoClickerCounter;
    
    private final static ImageIcon paperImg = new ImageIcon("Images\\paperImg.jpg");
    private final static ImageIcon clickerImg = new ImageIcon("Images\\mousePointer.png");
    private final static ImageIcon grayClickerImg = new ImageIcon("Images\\grayOutMousePointer.png");
    
    /**
     * Creates new form PaperClickerFrame
     */
    public PaperClickerFrame() {
        initComponents();
        initValues();
        
        setVisible(true);
    }

    private void initValues() {
        paperClicker.setIcon(paperImg);
        buyClicker.setIcon(grayClickerImg);
        clickCounter = 1;
        papersCounter = 0;
        initClickTime = true;
        firstClickTime = 0;
        autoClickerCounter = 0;
        paperCounter.setText(paperCounter.getText());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameNameLabel = new javax.swing.JLabel();
        paperClicker = new javax.swing.JButton();
        paperCounter = new javax.swing.JLabel();
        clicksPerSecondLabel = new javax.swing.JLabel();
        paperCounterLabel = new javax.swing.JLabel();
        clicksPerSecondCounter = new javax.swing.JLabel();
        buyClicker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gameNameLabel.setText("Paper Clickers!");

        paperClicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperClickerActionPerformed(evt);
            }
        });

        paperCounter.setText("0");

        clicksPerSecondLabel.setText("Clicks/Second:");

        paperCounterLabel.setText("Papers:");

        buyClicker.setMaximumSize(new java.awt.Dimension(40, 40));
        buyClicker.setMinimumSize(new java.awt.Dimension(40, 40));
        buyClicker.setPreferredSize(new java.awt.Dimension(40, 40));
        buyClicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyClickerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameNameLabel)
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(paperClicker, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paperCounterLabel)
                    .addComponent(clicksPerSecondLabel)
                    .addComponent(paperCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clicksPerSecondCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(buyClicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameNameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paperClicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paperCounterLabel)
                            .addComponent(buyClicker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(paperCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clicksPerSecondLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clicksPerSecondCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paperClickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paperClickerActionPerformed
        paperCounter.setText("" + papersCounter);
        clickCounter++;
        papersCounter++;
        
        if (Double.parseDouble(paperCounter.getText()) > 20) 
            buyClicker.setIcon(clickerImg);
        else
            buyClicker.setIcon(grayClickerImg);
        
        if (initClickTime) {
            initClickTime = false;
            firstClickTime = System.currentTimeMillis();
        }
        
        //Calculates the clicks per second everytime the button is clicked.
        clicksPerSecondCounter.setText(String.format("%.1f", 
                clickCounter / ((System.currentTimeMillis() - firstClickTime) / 1000)));
    }//GEN-LAST:event_paperClickerActionPerformed

    private void buyClickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyClickerActionPerformed
        if (Double.parseDouble(paperCounter.getText()) > 20) {
            paperCounter.setText("" + (Double.parseDouble(paperCounter.getText()) - 20));
            papersCounter = Double.parseDouble(paperCounter.getText()) - 20;
            autoClickerCounter++;
        }
    }//GEN-LAST:event_buyClickerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaperClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaperClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaperClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaperClickerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaperClickerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyClicker;
    private javax.swing.JLabel clicksPerSecondCounter;
    private javax.swing.JLabel clicksPerSecondLabel;
    private javax.swing.JLabel gameNameLabel;
    private javax.swing.JButton paperClicker;
    private javax.swing.JLabel paperCounter;
    private javax.swing.JLabel paperCounterLabel;
    // End of variables declaration//GEN-END:variables
}
